--Table structure for table 'message'
CREATE TABLE IF NOT EXISTS public.message 
(
	message_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	message_subject CHARACTER VARYING NOT NULL,
	message_body TEXT NOT NULL,
	message_created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	message_to INTEGER NOT NULL,
	message_from INTEGER NOT NULL,
	message_read BOOLEAN NOT NULL DEFAULT FALSE,
	message_archived BOOLEAN NOT NULL DEFAULT FALSE,
	CONSTRAINT message_pkey PRIMARY KEY (message_id)
);

-- Test data for message table--
INSERT INTO public.message (
    message_subject,
    message_body,
    message_to,
    message_from
  )
VALUES   (
    'Test Subject',
	'Test body message',
	19,
	21
  );

--Prepared statement for database query
SELECT i.*, c_to.*, c_from.account_id AS message_from_account_id, c_from.account_firstname AS message_from_firstname, c_from.account_lastname AS message_from_lastname
FROM public.message as i
JOIN public.account AS c_to ON i.message_to = c_to.account_id 
JOIN public.account AS c_from ON i.message_from = c_from.account_id 
WHERE i.message_to = 19